[package]
name = "db-utils"
version.workspace = true
edition.workspace = true

[dependencies]
storage = { workspace = true, features = ["json"]}
types.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json = "1.0.145"