[package]
name = "execute"
version.workspace = true
edition.workspace = true

[dependencies]
types.workspace = true
storage.workspace = true
anyhow.workspace = true

[dev-dependencies]
once_cell.workspace = true