[package]
name = "transaction"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
config.workspace = true
thiserror.workspace = true
rand.workspace = true
common.workspace = true
parity-scale-codec.workspace = true
types.workspace = true